using AutoMapper;
using Bogus;
using FluentAssertions;
using MiniHR.Application.POCOs.DTOs;
using MiniHR.Application.POCOs.VOs;
using MiniHR.Application.Services;
using MiniHR.Domain.Entities;
using MiniHR.Domain.Exceptions;
using MiniHR.Domain.Interfaces;
using Moq;
using System.Text.Json;
using Xunit.Abstractions;

namespace MiniHR.UnitTests.Services
{
    public class EmployeeServiceTests
    {
        // Subject Under Test (SUT)
        private readonly EmployeeService _employeeService;

        // Dependencies (Mocks)
        private readonly Mock<IEmployeeRepository> _mockRepo;
        private readonly Mock<IMapper> _mockMapper;

        //  * Define output helper for logging
        private readonly ITestOutputHelper _output;

        public EmployeeServiceTests(ITestOutputHelper output)
        {
            // * Assign output helper
            _output = output;

            // Initialize mocks
            _mockRepo = new Mock<IEmployeeRepository>();
            _mockMapper = new Mock<IMapper>();

            // Inject mocks into the SUT
            _employeeService = new EmployeeService(_mockRepo.Object, _mockMapper.Object);
        }

        [Fact] // Test case marker
        public async Task CreateEmployee_ShouldThrowDuplicateEmailException_WhenEmailExists()
        {
            // =========== Arrange ===========
            // Prepare a test DTO
            var dto = new EmployeeDTO
            {
                Email = "duplicate@minihr.com",
                FirstName = "Test",
                LastName = "User"
            };

            // Setup mock repository behavior (Mocking the dependency)
            // When GetByEmailAsync is called with the DTO's email, return an existing Employee object.
            _mockRepo.Setup(repo => repo.GetByEmailAsync(dto.Email))
                     .ReturnsAsync(new Employee { Id = Guid.NewGuid(), Email = dto.Email });

            // Define the action to be tested (Func<Task> to capture the exception)
            Func<Task> action = async () => await _employeeService.CreateEmployeeAsync(dto);

            // =========== Act & Assert ===========
            // Verify that the action throws the expected exception
            await action.Should().ThrowAsync<DuplicateEmailException>()
                .WithMessage($"Employee with email '{dto.Email}' already exists.");

            // Verify No Interaction: Ensure the AddAsync method was never called
            // `repo` is the mock instance of IEmployeeRepository
            _mockRepo.Verify(repo => repo.AddAsync(It.IsAny<Employee>()), Times.Never);
        }

        [Fact] // use Bogus to generate realistic test data
        public async Task CreateEmployee_ShouldReturnEmployeeVO_WhenDataIsValid()
        {
            // =========== Arrange ===========
            // 1. Generate a realistic EmployeeDTO using Bogus
            var dto = new Faker<EmployeeDTO>()
                .RuleFor(d => d.FirstName, f => f.Name.FirstName())
                .RuleFor(d => d.LastName, f => f.Name.LastName())
                .RuleFor(d => d.Email, f => f.Internet.Email())
                .RuleFor(d => d.Position, f => f.Name.JobTitle())
                .RuleFor(d => d.Salary, f => f.Finance.Amount(5000, 20000))
                .RuleFor(d => d.HireDate, f => f.Date.PastOffset())
                .Generate();

            // * Log the generated DTO for debugging purposes
            _output.WriteLine("========== data generated by Bogus ==========");
            _output.WriteLine(JsonSerializer.Serialize(dto, new JsonSerializerOptions { WriteIndented = true }));
            _output.WriteLine("======================================");

            // 2. Prepare the expected Employee entity (Mock Mapper's output)
            var expectedEntity = new Employee
            {
                Id = Guid.NewGuid(),
                Email = dto.Email,
                FirstName = dto.FirstName,
                LastName = dto.LastName
            };

            // 3. Setup Mock Repository: Return null for email check (success case)
            _mockRepo.Setup(r => r.GetByEmailAsync(dto.Email))
                     .ReturnsAsync((Employee?)null);

            // 4. Setup Mock Mapper: DTO -> Entity conversion
            _mockMapper.Setup(m => m.Map<Employee>(dto))
                        .Returns(expectedEntity);

            // 5. Setup Mock Mapper: Entity -> VO conversion
            _mockMapper.Setup(m => m.Map<EmployeeVO>(expectedEntity))
                        .Returns(new EmployeeVO
                        {
                            Id = expectedEntity.Id,
                            Email = expectedEntity.Email
                        });

            // =========== Act ===========
            var result = await _employeeService.CreateEmployeeAsync(dto);

            // =========== Assert ===========
            // 1. Verify return value correctness
            result.Should().NotBeNull();
            result.Id.Should().Be(expectedEntity.Id);
            result.Email.Should().Be(dto.Email);

            // 2. Verify AddAsync was called exactly once with the expected entity
            _mockRepo.Verify(r => r.AddAsync(expectedEntity), Times.Once);

            // 3. Verify SaveChangesAsync was called exactly once
            _mockRepo.Verify(r => r.SaveChangesAsync(), Times.Once);
        }

        [Fact]
        public async Task GetById_ShouldReturnNull_WhenEmployeeDoesNotExist()
        {
            // =========== Arrange ===========
            var nonExistentId = Guid.NewGuid();

            // Setup Mock Repo: Return null when searching by ID
            _mockRepo.Setup(repo => repo.GetByIdAsync(nonExistentId))
                     .ReturnsAsync((Employee?)null);

            // =========== Act ===========
            var result = await _employeeService.GetByIdAsync(nonExistentId);

            // =========== Assert ===========
            // Verify: result must be null
            result.Should().BeNull();

            // Verify: Repository was called once
            _mockRepo.Verify(repo => repo.GetByIdAsync(nonExistentId), Times.Once);
        }

        [Fact]
        public async Task GetById_ShouldReturnEmployeeVO_WhenEmployeeExists()
        {
            // =========== Arrange ===========
            var existingId = Guid.NewGuid();

            // Prepare the existing entity from the "database"
            var employeeEntity = new Employee
            {
                Id = existingId,
                FirstName = "Existing",
                LastName = "User",
                Email = "exist@minihr.com"
            };

            // Setup Mock Repo: Return the entity when searching by ID
            _mockRepo.Setup(repo => repo.GetByIdAsync(existingId))
                     .ReturnsAsync(employeeEntity);

            // Setup Mock Mapper: Map the Entity to a VO
            _mockMapper.Setup(m => m.Map<EmployeeVO>(employeeEntity))
                        .Returns(new EmployeeVO
                        {
                            Id = existingId,
                            FirstName = "Existing",
                            LastName = "User"
                        });

            // =========== Act ===========
            var result = await _employeeService.GetByIdAsync(existingId);

            // =========== Assert ===========
            // Verify: result must not be null
            result.Should().NotBeNull();

            // Verify: ID and names are correct
            result!.Id.Should().Be(existingId);
            result.FirstName.Should().Be("Existing");
            result.LastName.Should().Be("User");
        }
    }
}
